### ISSUE TITLE
align-self: opravit šipku v ilustraci

### ISSUE THREAD

**Issue by aleskrejci** [machal/prirucka#25]
Pokud něco v ranní rozespalosti nepřehlížím, v [css-align-self-schema.png](https://raw.githubusercontent.com/machal/prirucka/master/dist/images/small/vdgrid/css-align-self-schema.png) by měla být šipka vpravo zašedlá: https://github.com/machal/prirucka/blame/master/content/css-box-alignment.md#L63

**Comment by machal** [comment]
@aleskrejci Děkuji za hlášení přímo u zdroje. :-) Chybu vidím a opravím.
